### ISSUE TITLE
How to run the code examples

### ISSUE THREAD

**Issue by gungmas** [PacktPublishing/React-and-React-Native-Second-Edition#1]
Hi,

I'd like an example about how to set up my environment to run the code examples.

**Comment by adamboduch** [comment]
Hi @gungmas,

Sorry for the delay getting back to you. I've updated the README file to include instructions on running the examples:

Once you've cloned this repository, you can run each example throughout the
chapters as a standalone application. First, open a terminal and change into
the directory of the example that you want to run. For example:

```
cd Chapter02/builtin-html-tags
```

Then, you can install the dependencies for the example:

```
npm install
```

Finally, you can run the example:

```
npm start
```

This should open a web browser tab for you with the running app inside. In the
case of React Native examples, the process is similar. See chapter 13 for
steps on getting started with Expo and installing native IDEs.

Please let me know if you run into any other issues and I'll help you troubleshoot.

**Comment by gungmas** [comment]
Hi,

It worked as you suggested when downloading the code from GitHub but FYI it did not work with the code I downloaded earlier from Pact.
