### ISSUE TITLE
The examples in chapter 3 - 11 are not working.

### ISSUE THREAD

**Issue by gungmas** [PacktPublishing/React-and-React-Native-Second-Edition#2]
The public folder was missing so I copied it from chapter 2.

I also had to remove "postinstall": "node postinstall.js", from package.js to get the npm install to work.

**Comment by adamboduch** [comment]
@gungmas Sorry about that. I haven't had a chance to go through the rest of the chapters and fix them yet. I'll try to get at least some of that done today.
