### ISSUE TITLE
Missing data chapter 24

### ISSUE THREAD

**Issue by gungmas** [PacktPublishing/React-and-React-Native-Second-Edition#4]
The example in implementing-redux/mobile/actions/fetchArticles.js has this code:
return fetch(`http://192.168.86.24:3001/articles/${filter}`, 

That seems to be a local URL, how can I test this better?

**Comment by adamboduch** [comment]
@gungmas Are you just able to replace that with your own IP until I come up with something better?

**Comment by gungmas** [comment]
So what is read, a Node db or what?

**Comment by adamboduch** [comment]
@gungmas There's a `data.json` file in the `services` package. This is where data is read from.
