### ISSUE TITLE
Chapter 19 / selecting-options / Select.android.js

### ISSUE THREAD

**Issue by lentesta** [PacktPublishing/React-and-React-Native-Second-Edition#6]
These comments on lines 8 and 9 are incorrect - there's only one View component. It looks like it was copy-and-pasted from the iOS component:

> // It actually has two outer views that are
> // needed to get the styling right.

These two lines should be deleted from the code.

**Comment by adamboduch** [comment]
Will will fix this. Thanks for the report.
